# Generated by Django 4.2.4 on 2023-08-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_version_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='number',
            field=models.CharField(max_length=10, verbose_name='номер версии'),
        ),
    ]
